<?php

// hook
function aac_admin_menu_output_alter(&$content) {
	global $user;

	//test
	//dsm($content);
	
	// Change menu href from node/xxx to title name
	foreach($content['menu'] as &$internal_path) {
		$the_title = strtolower( $internal_path['#title'] );
		if($the_title == 'background') {
			$internal_path['#href'] = 'background';
		} 
		else if($the_title == 'links') {
			$internal_path['#href'] = 'links';
		}
		else if($the_title == 'about us') {
			$internal_path['#href'] = 'about-us';
		}
		else if($the_title == 'outcomes') {
			$internal_path['#href'] = 'outcomes';
		}
		else if($the_title == 'contact') {
			$internal_path['#href'] = 'contact';
		}
	}

  if($user->uid === 0) {
    // Anonymous user
		$content['account'] = NULL;
		$content['users'] = NULL;
		$content['search'] = NULL;
  }
	else if($user->roles && is_array($user->roles)) {
		foreach($user->roles as $key => $value) {
			if($value === 'admin') {
				$content['search'] = NULL;
				break;
			}
		}
	}
}


// hook_form_alter
function aac_form_alter(&$form, &$form_state, $form_id) {
	if($form_id === 'user_login') {
		$username_text = 'Enter your University of Melbourne username';
		$pass_text = 'Enter your University of Melbourne password';
		$form['name']['#title'] = $username_text;
		$form['pass']['#title'] = $pass_text;
	}
}
